# Generated by Django 3.2.8 on 2021-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=128, verbose_name='유저 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=32, verbose_name='유저 이름'),
        ),
    ]
