# Generated by Django 4.0 on 2021-12-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('user_score', models.IntegerField(max_length=32, primary_key=True, serialize=False, verbose_name='유저 점수')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
            ],
        ),
    ]
