# Generated by Django 4.0 on 2021-12-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userscore_id', models.CharField(max_length=32, verbose_name='유저 아이디')),
                ('userscore_nickname', models.CharField(max_length=32, verbose_name='유저 닉네임')),
                ('userscore_score', models.IntegerField(default=30, verbose_name='유저 점수')),
                ('userscore_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='점수 생성시간')),
                ('userscore_name', models.ForeignKey(db_column='userscore_name', on_delete=django.db.models.deletion.CASCADE, related_name='u_name', to='signup.user')),
            ],
            options={
                'verbose_name': '유저 점수',
                'verbose_name_plural': '유저 점수',
                'db_table': 'userscore',
            },
        ),
    ]
