# Generated by Django 4.0 on 2021-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisresultpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'verbose_name': '유저 점수', 'verbose_name_plural': '유저 점수'},
        ),
        migrations.AlterField(
            model_name='userscore',
            name='user_register_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='점수 생성시간'),
        ),
        migrations.AlterModelTable(
            name='userscore',
            table='userscore',
        ),
    ]
