# Generated by Django 4.0 on 2021-12-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisresultpage', '0002_alter_userscore_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='user_register_dttm',
        ),
        migrations.AlterField(
            model_name='userscore',
            name='user_score',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='유저 점수'),
        ),
    ]
